# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43b0f31019006811fe32b45aa9fa5d333dac6bb3f4d15903f82d7d0f4384cf6bea87e906f901943d7d79d6327fbeed273313268ee02cfb173eb96b0b920aa838

test:
  secret_key_base: 8afd4d488157d612168659526906b5de4134c7313c07c660656942c8a58b515732adcce91cacd18ed83c43482c23d5173ca9f36448b2e1af2fee2f16b53ee762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= Rails.env.production? ? File.read("/home/tw/apps/time-window/shared/SECRET_KEY_BASE").strip : nil %>
